### ISSUE TITLE
Password and secrets (intentionally!?) hardcoded

### ISSUE THREAD

**Issue by seisvelas** [kshivakumar/meddy-news#2]
The username and password for the Reddit account are right there, hardcoded.

https://github.com/kshivakumar/meddy-news/blob/b0757c72fd5a7a16c3728b446fb3fdde75f059cc/src/settings.py#L109-L116

Easy setup is absolutely not a good reason. Anyone could go in and delete that Reddit account at any time because you are making the password public.

**Comment by kshivakumar** [comment]
@seisvelas I used a temporary email to create the reddit and newapi accounts with dummy personal information. This project is just for demoing purpose. If someone does delete the reddit or newsapi accounts, it doesn't matter, I will create another one using a new temp email.

I wouldn't do this in my company or any production level code or any code that could have serious security implications. 

If you still feel I should remove those credentials, let me know.
